name: Build & Deploy Imhere
on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      
      - name: Get version
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }} # required for better experience using pre-releases
          fetch-depth: '0'

      - name: Create Release
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          PRERELEASE: true 

      - name: Install Dependencies
        run : yarn
      
      - name: Build
        run : yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 sync ./build s3://imhere-client
